
import type { Metadata } from "next";
import React from 'react';

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
    return (
        <div className="">
            {/* Main content area for the child pages */}
            <main className="">
                {children}
            </main>
        </div >
    );
}

export const metadata: Metadata = {
    title: "Insight hub",
    description: "Generated by create next app",
  };