
import type { Metadata } from "next";
import React from 'react';
import { HubProvider } from "@/context/HubContext";

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
    return (
        <div className="">
            <HubProvider>
                {children}
            </HubProvider>
        </div >
    );
}

export const metadata: Metadata = {
    title: "Insight hub",
    description: "Generated by create next app",
};