import type { Metadata } from "next";
import "./globals.css";
import { UserProvider } from '@/context/UserContext';

import Footer from "@/components/Footer";


export const metadata: Metadata = {
  title: "Exploding.io",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       
      >
        
        <UserProvider>
          {children}
        </UserProvider>
        <Footer />
      </body>
    </html>
  );
}
